### ISSUE TITLE
cant open config menu 1.20.1

### ISSUE THREAD

**Issue by ZombossXD** [Spyxar/TipTapShow#10]
when i press the bind to open up the config menu nothing happens and i have no clue what to do?

**Comment by Spyxar** [comment]
Do you have [ModMenu](https://modrinth.com/mod/modmenu) and [Cloth Config](https://modrinth.com/mod/cloth-config) installed?

**Comment by ZombossXD** [comment]
yes i have modmenu installed but it did not let me change it,i can try the other config

**Comment by Spyxar** [comment]
@ZombossXD was your issue resolved?

**Comment by Spyxar** [comment]
I'm assuming this was resolved. Closing issue.
