### ISSUE TITLE
right click speed is highly limited when using v1.5.0 (MC 1.20.2)

### ISSUE THREAD

**Issue by ItsPasi** [Spyxar/TipTapShow#13]
I noticed that when I use this mod and I want to place blocks I can only do this around once per second. Don't really know why and if it may have to do with another mod but right now this seems to be an issue on my end.

**Comment by Spyxar** [comment]
Are you able to reproduce this issue with only this mod and Fabric API installed? I can't seem to reproduce it myself.

**Comment by ItsPasi** [comment]
Yes, even with only these mods installed exactly like this I still have the issue. 

![grafik](https://github.com/Spyxar/TipTapShow/assets/12584747/d67ad183-2fbe-4fcb-9ab9-0c86d091a6e1)

**Comment by ItsPasi** [comment]
I made a quick **[video](https://www.youtube.com/watch?v=RbtfO5ubp-s)** showcasing the issue. I think its related to how long you click since the more CPS I have the less likely it will place a block.

**Comment by Spyxar** [comment]
If you check your latest.log (../.minecraft/logs/latest.log), does it say anything there? When I start an autoclicker at ~20 cps I can still place blocks.

**Comment by ItsPasi** [comment]
[latest.log](https://github.com/Spyxar/TipTapShow/files/13806633/latest.log)
Thats what it says. Also if I set my auto clicker to exactly these settings the right clicking will not place blocks at all. (left click still will break them)
![grafik](https://github.com/Spyxar/TipTapShow/assets/12584747/1ad5980f-dfcf-40e1-bc35-4f70757a298b)

So it does seem to have to do with how long you click down for a block to be placed.

**Comment by Spyxar** [comment]
Your log doesn't contain any errors, so that can be ruled out as a possible source of the problem. What happens if you click manually? Because Minecraft may not register all clicks if they're too fast.

**Comment by ItsPasi** [comment]
Nope its caused by the mod. Made another [video](https://youtu.be/T_rGrEheTDw) comparing this.

**Comment by Spyxar** [comment]
Do you have the same issue when you use v1.4.0 for 1.20.2? In v1.5.0 I fixed an issue with the right click CPS counter, which may have resulted in this bug.

**Comment by ItsPasi** [comment]
Yeah not an issue on the previous version

**Comment by Spyxar** [comment]
Can you try this? Made a small adjustment to the mixin.
[tiptapshow-1.6.0-BETA-TEST+1.20.2.zip](https://github.com/Spyxar/TipTapShow/files/13813813/tiptapshow-1.6.0-BETA-TEST%2B1.20.2.zip)

**Comment by ItsPasi** [comment]
Seems to still be happening on my end and didn't improve.

**Comment by Spyxar** [comment]
What Fabric Loader version are you using? I'm using 0.15.3 to test.

**Comment by ItsPasi** [comment]
Same version

**Comment by Spyxar** [comment]
I'm not sure what the issue could be, but could you also upload your debug.log? Also can you try not displaying the CPS and see if that changes anything, so I can be more sure of where the issue lies.

**Comment by ItsPasi** [comment]
I don't really know how to get a debug log, can't find it. For the other troubleshooting I tried that and did not solve the issue either, even disabling the overlay completely doesnt resolve it.

**Comment by Spyxar** [comment]
Should be located under ./minecraft/logs/debug.log, but it might be behind a setting.

**Comment by ItsPasi** [comment]
I don't have a debug.log so idk where to find it, def not in that folder

**Comment by Spyxar** [comment]
If anyone else experiences this, please comment below.

**Comment by Jerrycyx** [comment]
Yes, and I have the same problem. When I have this mod, the click speed is highly limited. Without it, there would be no problem.

**Comment by Felix14-v2** [comment]
> I can't seem to reproduce it myself.

You can use experience bottles to easily reproduce the bug. How it should be:

https://github.com/Spyxar/TipTapShow/assets/75726196/1de690e0-5735-422b-ad06-f06104cf465f

https://github.com/Spyxar/TipTapShow/assets/75726196/9164c63e-8460-4185-83e7-25b4da46a88b

How it is:

https://github.com/Spyxar/TipTapShow/assets/75726196/a6e7a396-e8d2-42fa-83d0-cb90e5d6f0e7

**Comment by Spyxar** [comment]
[tiptapshow-1.5.1+1.20.4.zip](https://github.com/Spyxar/TipTapShow/files/14379890/tiptapshow-1.5.1%2B1.20.4.zip) Could one of you try and see if this version works again?

**Comment by ItsPasi** [comment]
> [tiptapshow-1.5.1+1.20.4.zip](https://github.com/Spyxar/TipTapShow/files/14379890/tiptapshow-1.5.1%2B1.20.4.zip) Could one of you try and see if this version works again?

Yes. this issue appears resolved for me with that version of the mod!

**Comment by Felix14-v2** [comment]
Can confirm, the issue has been fully fixed

https://github.com/Spyxar/TipTapShow/assets/75726196/1fb924b9-7b8e-4fae-9c60-86cac644d532
