### ISSUE TITLE
I suggest adding the Ukrainian localization to the mod (I have already translated everything myself, you just need to add the file to the mod)

### ISSUE THREAD

**Issue by MrIDaki** [Spyxar/TipTapShow#14]
Localization file
[uk_ua.json](https://github.com/Spyxar/TipTapShow/files/14452932/uk_ua.json)

**Comment by Spyxar** [comment]
Did you happen to miss a few entries? It's no problem, just checking

**Comment by Spyxar** [comment]
Thanks for your contribution, translation is added in 1.6.0
