### ISSUE TITLE
PROBLEMS WITH COLORS

### ISSUE THREAD

**Issue by ManicTheRizzEZ** [Spyxar/TipTapShow#20]
I have a issue with colors. That didn't contain colors (HTML color codes). I know every HTML color code but whenever I writes there, it simply didn't works and the background of the Keystrokes goes like TRANSPARENT. I am having trouble with colors. Please pick this issue till tomorrow's 10:00 AM

**Comment by Spyxar** [comment]
Are you editing the values manually in the config file? When using cloth-config on the latest version you see this:
![image](https://github.com/user-attachments/assets/6e355e63-fdbe-43b4-a417-845fa12aad35)
However, in the config file the colors are converted to decimals, and look like this instead:
![image](https://github.com/user-attachments/assets/f3fd183d-2caf-48c7-823b-4384d8a06c56)

**Comment by Spyxar** [comment]
Has your issue been resolved? If so, I will close this issue.

**Comment by Spyxar** [comment]
Closed because of inactivity.
