### ISSUE TITLE
keystrokes are being limited with the mod playing on 1.5.0 MC1.20.2

### ISSUE THREAD

**Issue by BrightDarknessXX** [Spyxar/TipTapShow#23]
When playing with the mod, the rate at which the game receives clicks or keystrokes is being limited heavily.

**How to do:** Install this mod normally. Go in a world, throw snowballs as fast as you can spam the mouse.

**Expected result:** The snowballs get thrown as fast as you click the mouse.

**Actual result:** The rate at which the snowballs are thrown is slowed down significantly.

Which leaves me no choice to uninstall this mod.

**Comment by Spyxar** [comment]
This bug was only present on version 1.5.0, would it be a possibility to upgrade to a newer Minecraft version or downgrade to version 1.4.0 of the mod?

**Comment by BrightDarknessXX** [comment]
> This bug was only present on version 1.5.0, would it be a possibility to upgrade to a newer Minecraft version or downgrade to version 1.4.0 of the mod?

Thank you for your reply! I will test this out as soon as possible and get back to you, if that's OK for you.

**Comment by BrightDarknessXX** [comment]
Thank you for your knowledge and time! 1.4.0 is working for me.
