### ISSUE TITLE
how the fuck do i move the location of the keystrokes??

### ISSUE THREAD

**Issue by TDbea** [Spyxar/TipTapShow#25]
i might just be slow but idk

**Comment by Spyxar** [comment]
You can bind a keybinding to open the position gui, or you can change the value in the config with 2 sliders (you need to have cloth config for this to work)

**Comment by Spyxar** [comment]
Did you get it working? If so I'll close this issue

**Comment by Spyxar** [comment]
Closed because of inactivity.
