### ISSUE TITLE
Overlay text

### ISSUE THREAD

**Issue by BADRALOM** [Spyxar/TipTapShow#27]
I downloaded it for 1.20.1 and when I entered game it showed Right mouse button and left mouse button instead of RMS and LMS. I looked at ur comments and u r very kind. Can u please help me show it RMS and LMS ,  cuz it is weird and annoying that way . Pleaseeee help me with that.  i also posted a screeenshot so u can be clear with that.
![Screenshot 2024-12-26 231031](https://github.com/user-attachments/assets/9740f1e4-41e0-4612-8521-d69ecc54b07c)

**Comment by BADRALOM** [comment]
> if you are free and wanna contact me, email me at [rajaubaidullah35@gmail.com](mailto:rajaubaidullah35@gmail.com)
or if u wann contact me thorugh discord , contact on       "ubaidullah35"       in discord

**Comment by Spyxar** [comment]
This issue has been resolved via Discord, the underlying issue will be fixed in an upcoming release.
