### ISSUE TITLE
Keystrokes positioning 

### ISSUE THREAD

**Issue by Xeoolol** [Spyxar/TipTapShow#3]
Do you have a feature where I can move the keystrokes position?

**Comment by Spyxar** [comment]
Yep, this feature exists. You can access it by going to the mods menu (assuming you have both [Mod Menu](https://modrinth.com/mod/modmenu) and [Cloth Config](https://modrinth.com/mod/cloth-config) installed) and then clicking this icon after selecting TipTapShow from the list on the left.
![image](https://user-images.githubusercontent.com/81620237/230958864-4b9622ee-5c4d-46b4-938b-ba585d5a3a29.png)

If you then scroll down a little you will see the options "Horizontal Display" and "Vertical Display", editing these will move the keystrokes around.
![image](https://user-images.githubusercontent.com/81620237/230959245-4a7e88dd-e007-4e3b-a8d9-2dd3027d393a.png)

Hope this helps you, if you have any other questions feel free to ask!
