### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Fab-Plays** [Spyxar/TipTapShow#4]
Whenever I Open Config The Game Crashes in v 1.3.1 .

**Comment by Spyxar** [comment]
What Minecraft version are you using v1.3.1 on?

**Comment by Fab-Plays** [comment]
I am playing on 1.19.4 fabric

**Comment by Spyxar** [comment]
Could you upload your latest.log to a site like pastebin and post the link here? The cause of the crash might be that a valid ModMenu / ClothConfig installation is missing but I can't be sure.

**Comment by Fab-Plays** [comment]
https://pastebin.com/Vx7F7YDB
This will show the crash report.
And tell me if there is a command in game to open config menu ill try that too and tell u if it crashes.
And I play cracked minecraft so tell me if there is a problem with that.

**Comment by Spyxar** [comment]
Looks like you're missing ModMenu, it's not supposed to crash in that case though. I'll try to get out a fix for that in a few hours.

**Comment by Fab-Plays** [comment]
I downloaded ModMenu now it works thanks.
