### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Fab-Plays** [Spyxar/TipTapShow#5]
You should also add crouch to the mod

**Comment by Fab-Plays** [comment]
You should also make it that we can control the speed of rainbow mode

**Comment by Spyxar** [comment]
> You should also add crouch to the mod

Where would you it to be displayed (since changing the order isn't supported yet)?

**Comment by Fab-Plays** [comment]
It Can be in a new column below the spacebar which shows crouching and sprinting.

**Comment by Spyxar** [comment]
The rainbow speed option you requested is likely to be in the next big update, the feature is finished it just needs some more testing.

For the crouching you can follow #12.
