### ISSUE TITLE
Salwyrr client like/modern appearance

### ISSUE THREAD

**Issue by ItsPasi** [Spyxar/TipTapShow#8]
I was thinking this mod could look much nicer if you would be able to make it look similar to how it is on the [salwyrr client](https://www.youtube.com/watch?v=YHlJF8hRihc).
It has the addition of visual mouse movement and rounded corners. I think just rounded corners alone with more color options (option to change opacity and color of both BG and Text in both states) would make it look much nicer with more customizability.

I made this concept in photoshop which i think could work pretty well 
![grafik](https://github.com/Spyxar/TipTapShow/assets/12584747/1f5d4a63-3a18-4ea1-8554-c12373c3a6e6)

**Comment by Spyxar** [comment]
Rounded corners will be in v1.5.0, which will be released shortly. Can't promise anything on the other features you proposed.

**Comment by ItsPasi** [comment]
I love the addition of rounded corners in the new version! I think if you could add CTRL and SHIFT as options to display that would be great (not as icons as in my example but just as text buttons). But still love it much more already.

**Comment by Spyxar** [comment]
Glad to hear you like the new rounded corners! As for the other display options you can follow #12.
Can this issue be closed, or do you have any other questions?
